### ISSUE TITLE
ATAcontrol.get_ant_pos() doesn't work

### ISSUE THREAD

**Issue by daniestevez** [SETIatHCRO/ATA-Utils#1]
It seems that 

https://github.com/SETIatHCRO/ATA-Utils/blob/3c81bcd05428b2489a433be2056b075b7dd0eba3/pythonLibs/ATATools/ata_control.py#L135

doesn't work:

```
>>> ac.get_ant_pos(['1h','4g'])
process '['ssh', 'obs@control', 'fxconf.rb', 'antpos']' returned error
 b"usage: fxconf [-h] [--host HOST] [-p PORT] {help,sals,sagive} ...\nfxconf: error: argument operation: invalid choice: 'antpos' (choose from 'help', 'sals', 'sagive')\n"
```

The problem is that the `fxconf.rb` at `control` doesn't accept the `antpos` argument that `get_ant_pos()` uses to call it.

**Comment by wfarah** [comment]
I'm afraid this is a more nested issue. `fxconf.rb` now points to another, newly-developed, python script to replace the original one that had compatibility issues with the new `obs` machine. Maybe a quick hack would be to get the NEU antenna positions manually and host some csv file somewhere for all to see.

@tkoumrian are the antenna positions hosted on a file/database on `control`?

**Comment by tkoumrian** [comment]
`get_ant_pos()` has been fixed in two ways.

I've added the "antpos" command to fxconf.py/fxconf.rb, so the original ssh implementation of `get_ant_pos()` now works again.

For the future, the ssh call is replaced with a direct call to a REST api.

**Comment by daniestevez** [comment]
I confirm that `get_ant_pos()` is now working, so I'm closing this.
