### ISSUE TITLE
atacheck REST equivalent

### ISSUE THREAD

**Issue by wfarah** [SETIatHCRO/ATA-Utils#15]
An enhancement to the REST API is to add support to call an `atacheck`. 
This will help with implementing logic inside the python observing scripts

**Comment by tkoumrian** [comment]
Rise and set time are in TAI nanoseconds instead of datetime, but that's the fault of the existant code upstream that needs fixing.  This interface to the REST call is complete however.

**Comment by tkoumrian** [comment]
@wfarah `check_source()` now returns POSIX UTC timestamp and python UTC timezone `datetime` for rise/set times.
