### ISSUE TITLE
make_and_track_ephems doesn

### ISSUE THREAD

**Issue by wfarah** [SETIatHCRO/ATA-Utils#2]
The function `make_and_track_ephems`: 

https://github.com/SETIatHCRO/ATA-Utils/blob/ata-rest/pythonLibs/ATATools/ata_control.py#L294

should wait until antennas have fully acquired position before returning to replicate the behaviour of the previous function (`atatrackephem -w ...`). Currently, observing scripts can start calibrating/observing while the antennas are slewing

**Comment by tkoumrian** [comment]
@wfarah You can try an experiment of adding key/value pair in the dict JSON parameters to the put() call on line 309 `’wait’: True` And try to see if it works or you get a timeout exception.  It can be a long time to get on source, and this might hit a server timeout.  Let me know what happens, or I can test it sometime when the array is free.

**Comment by wfarah** [comment]
@tkoumrian the wait calls seem to work for the functions you have edited. However, I tried adding `json={'wait': True}` to the `set_az_el` and `park_antennas` functions, but the calls didn't seem to block. Are there changes that need to happen on the `ata_rest` side for these edits to take effect? I think once these are implemented, this issue can be closed, and we can merge the branches.
