### ISSUE TITLE
Adding default hashpipe targets

### ISSUE THREAD

**Issue by wfarah** [SETIatHCRO/ATA-Utils#24]
To make it easier on observers, why not have hashpipe target templates already available for the seti-nodes? We know for a fact that LOb and LOc are independently passed to seti-nodes1-4 and 5-8 respectively. 
https://github.com/SETIatHCRO/ATA-Utils/blob/dc53d7aecfe48364f11cc9fce2ebd28fff4cb602/pythonLibs/SNAPobs/snap_hpguppi/record_in.py#L104

Something like:
```
from defaults import LOb_targets # or something similar
record_in(10, 300, LOb_targets)
```

**Comment by radonnachie** [comment]
👍 
https://github.com/SETIatHCRO/ATA-Utils/commit/682aac535eceef97ddd70bed77eb0bb172136cc7

Tested with:
```
from SNAPobs.snap_hpguppi import record_in as hpguppi_record_in
from SNAPobs.snap_hpguppi import snap_hpguppi_defaults as hpguppi_defaults

hpguppi_record_in.record_in(
	5, 5,
	hashpipe_targets = hpguppi_defaults.hashpipe_targets_LoC,
	dry_run=True
)
```

Installed at the ATA in the `rfsoc8bit` conda environment.
