### ISSUE TITLE
requests needs to be added to pythonLibs requirements

### ISSUE THREAD

**Issue by daniestevez** [SETIatHCRO/ATA-Utils#4]
With the addition of the REST backend, requests is now used in `pythonLibs`, so it should be added as a requirement in `pythonLibs/setup.py`. Otherwise `import ATATools.ata_control` will give an `ImportError` saying it can't find requests.

**Comment by wfarah** [comment]
Weird GitHub didn't notify me about this.
Tagging @tkoumrian

**Comment by tkoumrian** [comment]
Added the requirement.  Successfully tested that it was installed during setup, so will close.  Reopen if you have a problem with it.
