### ISSUE TITLE
ata_control.create_ephems2() issue with negative offset

### ISSUE THREAD

**Issue by wfarah** [SETIatHCRO/ATA-Utils#7]
After running `ata_control.create_ephems2(source, az_offset, el_offset)` with `az_offset` < 0, `ata_control.point_ants2(source, "off", ant_list)` doesn't actually make the antennas point to the off-source and it returns instantaneously without an error message.

**Comment by tkoumrian** [comment]
The problem is non-robust argument string parsing in ata Java code repo for tracking is treating the negative offset as a `-argument_name` instead of a negative value.  Will fix.

**Comment by tkoumrian** [comment]
Fixed in https://github.com/SETIatHCRO/ata/issues/1

**Comment by wfarah** [comment]
Tested and confirmed it works
