### ISSUE TITLE
Porting `atalistsats` to `ATATools`

### ISSUE THREAD

**Issue by wfarah** [SETIatHCRO/ATA-Utils#9]
Request:
A function that returns a similar output to `atalistsats` (assuming is interfaceable via REST) with the optional flags that the command-line tool provides, but from within ATATools.

**Comment by tkoumrian** [comment]
Take a look at atasats for comparison.  It has an advantage that it says indicates rising or setting over the ATA.

**Comment by tkoumrian** [comment]
Do you want just the text output suitable for viewing, or do you want it organized in a data structure?

**Comment by wfarah** [comment]
I want it in a data structure to be able to write logic around what satellite to observe and when etc.

**Comment by wfarah** [comment]
Added a new submodule to wrap around the REST call:
https://github.com/SETIatHCRO/ATA-Utils/blob/master/pythonLibs/ATATools/ata_sources.py

I'll close the issue
